{:user {:plugins [[codox "0.6.6"]
                  [lein-ancient "0.4.4"]
                  [lein-difftest "1.3.8"]
                  [lein-ritz "0.7.0"]
                  [lein-bikeshed "0.1.3"]
                  [lein-try "0.3.0"]
                  [lein-exec "0.3.1"]
                  [lein-vanity "0.1.0"]
                  [jonase/eastwood "0.0.2"]
                  [lein-kibit "0.0.8"]
                  [com.aphyr/prism "0.1.1"]
                  [com.jakemccrary/lein-test-refresh "0.1.2"]
                  [quickie "0.2.2"]
                  [lein-typed "0.3.1"]
                  [lein-marginalia "0.7.1"]
                  [org.timmc/nephila "0.2.0"]
                  [lein-cloverage "1.0.2"]
                  [com.jakemccrary/lein-test-refresh "0.1.2"]]
        :repl-options {:nrepl-middleware [troncle.discover/wrap-discover]}
        :aliases {"slamhound" ["run" "-m" "slam.hound/main"]}
        :dependencies [[ritz/ritz-nrepl-middleware "0.7.0"]
                       [org.clojure/tools.namespace "0.2.4"]
                       [org.clojure/tools.trace "0.7.6"]
                       [org.clojars.gjahad/debug-repl "0.3.3"]
                       [org.clojure/core.typed "0.2.13"]
                       [night-vision "0.1.0-SNAPSHOT"]
                       [slamhound "1.5.0"]
                       [alembic "0.2.0"]
                       [riddley "0.1.0"]
                       [troncle "0.1.2-SNAPSHOT"]
                       [wally "0.1.1"]
                       [com.cemerick/pomegranate "0.2.0"]
                       [com.aphyr/prism "0.1.1"]]}}
