{:user {:plugins [[lein-ancient "0.4.4"]
                  [lein-difftest "1.3.8"]
                  [lein-ritz "0.7.0"]
                  [jonase/eastwood "0.0.2"]
                  ;; [jonase/eastwood "0.0.3"]
                  [lein-kibit "0.0.8"]
                  [org.timmc/nephila "0.2.0"]
                  [lein-cloverage "1.0.2"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}
        :dependencies [[ritz/ritz-nrepl-middleware "0.7.0"]
                       [org.clojure/tools.namespace "0.2.4"]
                       [criterium "0.4.1"]
                       [slamhound "1.5.0"]
                       [print-foo "0.4.7"]
                       [alembic "0.2.0"]
                       [com.cemerick/pomegranate "0.2.0"]]}}
